CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "username" varchar UNIQUE NOT NULL,
  "first_name" varchar,
  "last_name" varchar,
  "role" varchar,
  "phone" BigInt DEFAULT null,
  "email" varchar UNIQUE NOT NULL,
  "is_verified" bool,
  "password" varchar NOT NULL,
  "user_metadata" varchar DEFAULT null,
  "last_login" datetime,
  "created_at" datetime DEFAULT (now()),
  "updated_at" datetime
);

CREATE TABLE "query" (
  "query_id" int PRIMARY KEY,
  "fk_user_id" int,
  "fk_pdf_id" int,
  "query_text" varchar,
  "query_response" varchar,
  "query_timestamp" datetime DEFAULT (now()),
  "response_timestamp" datetime,
  "is_answered" bool
);

CREATE TABLE "admin" (
  "admin_id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "fk_user_id" int,
  "last_login" datetime
);

CREATE TABLE "pdf" (
  "pdf_id" int PRIMARY KEY,
  "fk_user_id" int,
  "pdf_file" varchar,
  "title" varchar,
  "description" varchar,
  "upload_timestamp" datetime DEFAULT (now()),
  "tokenized_text" varchar,
  "other_metadata" varchar
);

CREATE TABLE "collection" (
  "collection_id" int PRIMARY KEY,
  "fk_user_id" int,
  "fk_pdf_id" int,
  "collection_name" varchar DEFAULT 'New Collection',
  "collection_timestamp" datetime DEFAULT (now())
);

CREATE TABLE "interaction" (
  "interaction_id" int PRIMARY KEY,
  "fk_user_id" int,
  "fk_collection_id" int,
  "timestamp" datetime DEFAULT (now()),
  "interaction_type" varchar,
  "interaction_details" varchar
);

CREATE TABLE "sso_tokens" (
  "token_id" int PRIMARY KEY,
  "fk_user_id" inf,
  "token" int
);

COMMENT ON COLUMN "users"."user_metadata" IS 'any other info about user';

COMMENT ON COLUMN "pdf"."other_metadata" IS 'any other data that might be required';

ALTER TABLE "query" ADD FOREIGN KEY ("fk_user_id") REFERENCES "users" ("id");

ALTER TABLE "query" ADD FOREIGN KEY ("fk_pdf_id") REFERENCES "pdf" ("pdf_id");

ALTER TABLE "admin" ADD FOREIGN KEY ("fk_user_id") REFERENCES "users" ("id");

ALTER TABLE "pdf" ADD FOREIGN KEY ("fk_user_id") REFERENCES "users" ("id");

ALTER TABLE "collection" ADD FOREIGN KEY ("fk_user_id") REFERENCES "users" ("id");

ALTER TABLE "collection" ADD FOREIGN KEY ("fk_pdf_id") REFERENCES "pdf" ("pdf_id");

ALTER TABLE "interaction" ADD FOREIGN KEY ("fk_user_id") REFERENCES "users" ("id");

ALTER TABLE "interaction" ADD FOREIGN KEY ("fk_collection_id") REFERENCES "collection" ("collection_id");

ALTER TABLE "sso_tokens" ADD FOREIGN KEY ("fk_user_id") REFERENCES "users" ("id");
